# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
#version: 2
#jobs:
#  build:
#    docker:
#      # specify the version you desire here
#      - image: circleci/node:7.10
#
     # Specify service dependencies here if necessary
     # CircleCI maintains a library of pre-built images
     # documented at https://circleci.com/docs/2.0/circleci-images/
     # - image: circleci/mongo:3.4.4

#    working_directory: ~/syos-drphillipscenter

#    steps:
#      - checkout

     # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          - v1-dependencies

#      - run: yarn install

#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}

     # run tests!
#      - run: yarn test
#      - run: yarn build

#      - persist_to_workspace:
#          root: ~/syos-drphillipscenter
#          paths:
#            - dist

#  deploy-test:
#    docker:
#      - image: circleci/node:7.10
#    working_directory: ~/syos-drphillipscenter
#    steps:
#      - attach_workspace:
#          at: ~/syos-drphillipscenter
#      - run: sudo apt install python-pip python-dev
#      - run: sudo pip install awscli
#      - run:
#          name: Deploy to S3 if tests pass and branch is develop
#          command: |
#            echo "Deploying develop branch to unstable"
#            aws s3 sync ~/syos-drphillipscenter/dist s3://made-syos/drphillipscenter/releases/unstable/ --cache-control 'max-age=60, no-transform, public' --acl public-read

#  deploy-staging:
#    docker:
#      - image: circleci/node:7.10
#    working_directory: ~/syos-drphillipscenter
#    steps:
#      - attach_workspace:
#          at: ~/syos-drphillipscenter
#      - run: sudo apt install python-pip python-dev
#      - run: sudo pip install awscli
#      - run:
#          name: Deploy to S3 if tests pass and branch is master
#          command: |
